<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-A7C74EC" failures="1" tests="2" name="Default test(failed)" time="26.735" errors="0" timestamp="2023-01-06T08:23:37 IST">
  <testcase classname="TestCases.FailedTestPractice" name="verifyLoginLogoTest" time="0.073">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.FailedTestPractice.verifyLoginLogoTest(FailedTestPractice.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginLogoTest -->
  <testcase classname="TestCases.FailedTestPractice" name="verifyProductsTest" time="3.628"/>
  <testcase classname="TestCases.FailedTestPractice" name="verifyLoginToTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLoginToTest -->
  <testcase classname="TestCases.FailedTestPractice" name="verifyCurrentUrlTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyCurrentUrlTest -->
  <testcase classname="TestCases.FailedTestPractice" name="verifyTitleTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyTitleTest -->
  <testcase classname="TestCases.FailedTestPractice" name="verifyBotLogoTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyBotLogoTest -->
</testsuite> <!-- Default test(failed) -->
